apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      env: web
  template:
    metadata:
      name: myweb-pod
      labels:
        env: web
    spec:
      containers:
      - name: myweb-con
        image: httpd